### ISSUE TITLE
Packages not properly published to npm.io (files are missing)

### ISSUE THREAD

**Issue by radandevist** [Darginec05/Yoopta-Editor#104]
**Describe the bug**
Typescript won't stop yelling at me after I installed '@yoopta/editor' with pnpm. So I went digging in my node_modules folder and turns out there are no files at all (only a package.json and a readme.md) in the package folder.
There is a beta 'code' tab on npm.io and it seems to confirm what I am telling about.

**Comment by innocentamadi** [comment]
Yup. Same here. Can confirm this is the case. @Darginec05 could you help look into it?

**Comment by Darginec05** [comment]
Hmm 🤔
Checking it

**Comment by Darginec05** [comment]
Thanks for this issue guys 🙌 
I fixed it in @2.0.1
