### ISSUE TITLE
Customizable ElementActions

### ISSUE THREAD

**Issue by joaotessarolo** [Darginec05/Yoopta-Editor#109]
Hello, i tried change the color of left elements of editor, but they are svg.

<img width="164" alt="Captura de Tela 2024-02-14 às 10 46 27" src="https://github.com/Darginec05/Yoopta-Editor/assets/83466473/e874324c-e761-4f9b-bfe5-26346faab895">

If there is no option to modify them, I leave here my suggestion so that this can happen, because my page is in dark mode, and in dark mode it looks like this:

<img width="156" alt="Captura de Tela 2024-02-14 às 10 50 13" src="https://github.com/Darginec05/Yoopta-Editor/assets/83466473/2d7f87b3-4813-43a3-aaf6-f20dfc2d02b9">

**Comment by Darginec05** [comment]
Hi @joaotessarolo.
The color for these svg's can be changed as follows: 
``` 
.yoopta-element-actions button {
  color: <your color>
}
```

**Comment by Darginec05** [comment]
I'll close this issuee. 
Reopen if bug is still reproduced
