### ISSUE TITLE
Bug: Copy/Paste content from Notion to Editor

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yoopta-Editor#110]
**Describe the bug**

Copy/paste from notion doesn't work properly.

**To Reproduce**
1. Go to notion
2. Select a few blocks in the content (in my case: paragraph that has link and a list of checkboxes)
3. Click cmd + C (copy)
4. Go to editor
5. Set the cursor at any place
6. Paste the content (cmd + V)
7. I got only text from paragraph

**Expected behavior**
After I paste the content, I expect all the content I copied:
- paragraph with the link
- list of checkboxes
- checkboxes should keep the state (checked/not checked)

**Screenshots**
![ezgif-6-8428e30bd7](https://github.com/Darginec05/Yoopta-Editor/assets/3044387/2e5d91b7-f816-47d0-9176-bc11b896f833)

**Desktop (please complete the following information):**
 - OS: 13.4.1 (22F82)
 - Browser: Chrome
 - Version 121.0.6167.160 (Official Build) (arm64)

**Comment by Darginec05** [comment]
This task is done

Versions:
- yoopta/editor@4.0.0

Demos:
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup
