### ISSUE TITLE
Allow multiple nesting of todo items in todolist

### ISSUE THREAD

**Issue by piekarar** [Darginec05/Yoopta-Editor#113]
**Is your feature request related to a problem? Please describe.**
Currently we have only 1 step of depth for todolist

**Describe the solution you'd like**
Have at least 4 steps of depth, similar to what it is in Notion

**Comment by Darginec05** [comment]
Thanks for reporting!
It will be available in next major version @v4

**Comment by Darginec05** [comment]
This is done in v4.0.0
Check example with custom divider plugin: 
 - https://stackblitz.com/edit/vitejs-vite-syjdcx
