### ISSUE TITLE
[FEATURE] <How to customize this part of ui>

### ISSUE THREAD

**Issue by gonghaibo** [Darginec05/Yoopta-Editor#121]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

pic
![WX20240421-181103@2x](https://github.com/Darginec05/Yoopta-Editor/assets/36252719/5b6af33e-d0b1-47f9-82cf-fae13b5d25a7)How to customize this part of ui

### Proposed Solution

how?

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Thank you for reporting issue.
Do you mean fully custom rendering or just adding some styles to every item?

**Comment by Darginec05** [comment]
Added classnames for this in v4.3.0
Check example and docs:

https://yoopta-editor.vercel.app/examples/withCustomStyles#dc2f645d-48dc-467c-aae3-086b5913e3a2
