### ISSUE TITLE
[BUG] don't use id="yoopta-editor" and make it possible to have multiple independend editors on the page

### ISSUE THREAD

**Issue by maZahaca** [Darginec05/Yoopta-Editor#126]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

For now, editor uses strick id="yoopta-editor" hardcoded, which prevents from using multiple editors on the page,

### Steps to Reproduce

- try to add multiple editors on the page

### Environment

- OS: MacOS
- Browser: Chrome

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.3.0
