### ISSUE TITLE
[BUG] When clicking on a link is not going to the link

### ISSUE THREAD

**Issue by Lfrancos** [Darginec05/Yoopta-Editor#138]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

You can see that there are a lot of links in the [preview](https://yoopta-editor.vercel.app/examples/withBaseFullSetup)  but I'm not able to click to go to the link.

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to the [example](https://yoopta-editor.vercel.app/examples/withBaseFullSetup) page.
2 scroll down
3. When you see "Do you like it? Please star our repo in Github.
4. You should be able to click on "Our repo in Github". But I'm not able to.

### Environment

- Windows 11:
- Browser: Chrome

### Do you want to work on this issue?

No

**Comment by Nitin6404** [comment]
I would like to work on it

**Comment by maZahaca** [comment]
@Nitin6404 Here is the [dev community](https://t.me/YooptaEditor), feel free to join and get in touch with us.

**Comment by Darginec05** [comment]
Thanks for reporting! This is good point. 
Links are working good when editor is read only, but it should work for edit mode also. 
This is how I see the solution to this problem with a good approach to UX:
1. When you hover over  link in edit mode, something like a small button should be displayed over it
<img width="534" alt="Screen Shot 2024-05-07 at 16 36 41" src="https://github.com/Darginec05/Yoopta-Editor/assets/29093118/b2c14d48-8292-446b-b789-b4f90886228a">

2. So, when you click on edit it should show Link editor from `@yoopta/link-tool` package
<img width="507" alt="Screen Shot 2024-05-07 at 16 39 47" src="https://github.com/Darginec05/Yoopta-Editor/assets/29093118/864db9ae-2b24-4bae-ad91-5a4c72dd98a9">

3. To access to Link editor from `@yoopta/link-tool` package (if it passed to props `tools`) we can use `useTools` hook


@Nitin6404 It would be great! 
Currently we are working on documentation for contribution.
Join to our community - https://t.me/YooptaEditor

**Comment by Darginec05** [comment]
Done in @v4.6.4
https://github.com/user-attachments/assets/d6f21270-0ba6-4477-95fc-3099ca98deb7
