### ISSUE TITLE
[BUG] It is difficult to know what item I'm selecting on the "Action Menu"

### ISSUE THREAD

**Issue by Lfrancos** [Darginec05/Yoopta-Editor#139]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When I open the "Action Menu" (I'm referring to the menu that you open with "/")  it would be nice to know what you are about to select. 

### Steps to Reproduce

For example:

1. I want to create a "Heading 3"
2. Press "/" to get the "Action Menu"
3. Press the arrow down but I'm not able to see what element I'm about to select. 

### Environment

- Windows 11:
- Browser: Chrome

### Screenshots

Here if I press "enter" I will create a "Heading 3" but it is really hard to know.
<img src="https://github.com/Darginec05/Yoopta-Editor/assets/91067003/de10a386-61b6-4819-b3c7-7236f2b60e41" width=50% height=50%>

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Hi @Lfrancos, thanks for reporting. 
But the selected element is colored in background color (this is shown even in your screenshot)

**Comment by Lfrancos** [comment]
Hi @Darginec05, happy to help with things that I see.

Are you saying that you are able to differentiate that I'm about to select Heading 3 instead of Heading 2 in that screen shot??

**Comment by Lfrancos** [comment]
Hi @Darginec05 I'm looking at this from another screen and now I'm seeing it. It must be a problem with the other screen that I was using! sorry for the confusion. Thank you.

**Comment by Darginec05** [comment]
No problem 😊
Thanks
