### ISSUE TITLE
[FEATURE] Missing function editor.setEditorValue(value)

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yoopta-Editor#143]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Here's a function to get the editor content (document)
`const editorContent = editor.getEditorValue();`

but no way to set it with similar function `editor.setEditorValue(value);`

### Proposed Solution

Implement function `editor.setEditorValue(value);` that also should rerender YoptaEditor component

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Added in v4.2.0
