### ISSUE TITLE
[BUG] Yoopta CSS selectors for button is too high

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yoopta-Editor#148]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

I can't use my 
MUI components in my custom plugins

Here's css selectors that limits me
On 3d page you can see that my background-color isn't applied for hover state

![2024-05-11 17 40 28](https://github.com/Darginec05/Yoopta-Editor/assets/3044387/f77e38eb-cda1-46c6-bf86-f07c8bd69871)
![2024-05-11 17 40 12](https://github.com/Darginec05/Yoopta-Editor/assets/3044387/70d4ad7e-71eb-469c-8231-0eac714e8355)
![2024-05-11 17 41 34](https://github.com/Darginec05/Yoopta-Editor/assets/3044387/acbe8f02-bb7f-4945-bb67-5fdeaa5f553d)

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Create new custom Plugin
2. Render a MUI button
3. It gets yoopta styles instead of MUI

### Environment

- OS: MacOS 13.6.6 (22G630)
- Browser: Chrome Version 124.0.6367.119 (Official Build) (arm64)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Related to https://github.com/Darginec05/Yoopta-Editor/issues/126

**Comment by Darginec05** [comment]
Fixed in v4.3.0
Check example and docs:
- https://yoopta-editor.vercel.app/examples/withCustomStyles
