### ISSUE TITLE
Set PlaceHolder Value For When Editor Is Not Focused. 

### ISSUE THREAD

**Issue by AhmxdNYC** [Darginec05/Yoopta-Editor#152]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I’m making a social media like application with an editor for creating a post. 

I want the default placeholder for when editor is not focused to be something like : Start Your Story… 

And when editor is focused for it to be type / for the / menu 

so the user can see where to start their story and also know about / menu at the same time 

Also recommended also adding options for editing placeholder value for each item in the editor. 

ex after you do /heading you get a new placeholder : 
Type your heading… 

thank you 

### Proposed Solution

Don’t have a solution. 

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.4.0.
Added three new API methods: 
- editor.isFocused()
- editor.focus()
- editor.blur()

Docs
- https://github.com/Darginec05/Yoopta-Editor/tree/master/packages/core/editor#api-from-editor-instance

Examples
- https://yoopta-editor.vercel.app/examples/withEditorFocusBlur
