### ISSUE TITLE
[PLUGIN] Table Plugin

### ISSUE THREAD

**Issue by j7-dev** [Darginec05/Yoopta-Editor#157]
### Is this a unique plugin request?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Proposed Plugin Solution

help user to edit table easily

Example:  Editor.js's table plugin

https://github.com/editor-js/table

### Screenshots

![image](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/3fab0bae-c905-4f12-a607-dfd9c7983437)

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Umm...I might clone the [editor-js/table](https://github.com/editor-js/table) projector

Then try to understand how they implement the features, if it's not too hard

Then re-implement the feature with Yoopta-Editor's plugin boilerplate if exist

**Comment by maZahaca** [comment]
@j7-dev, thanks for reporting this plugin request! We are super excited to see your willingness to work on it.

You can check back on [that discussion](https://github.com/Darginec05/Yoopta-Editor/discussions/134) about the Table plugin. It might be helpful to see other implementation options. I also added yours to the discussion.

Also, consider joining our [Telegram Dev Community](https://t.me/YooptaEditor), where we can respond faster and discuss it in detail.

**Comment by maZahaca** [comment]
At the moment, we're aiming to merge https://github.com/Darginec05/Yoopta-Editor/pull/156 and https://github.com/Darginec05/Yoopta-Editor/pull/151, which would help with contributing experience.

**Comment by maZahaca** [comment]
@j7-dev We're excited as both mentioned improvements just got merged. It's a great time to start coding! Yay 🎉 
Please check [CONTRIBUTING.md](https://github.com/Darginec05/Yoopta-Editor/blob/master/CONTRIBUTING.md) to get the steps started.
If you see how we can improve the contributing guide, please let us know 🙏

**Comment by j7-dev** [comment]
@maZahaca 

ok, I might start, these days.

I'm new to Yoopta-Editor, do Yoopta-Editor have any plugin boilerplate?

**Comment by Darginec05** [comment]
@j7-dev During today, I'll create script to create template for new plugins

**Comment by Darginec05** [comment]
@j7-dev Hi! 
If you still have plans to implement Table plugin I have good news for you. 
I published [v4.5.0](https://github.com/Darginec05/Yoopta-Editor/releases/tag/v4.5.0) with new API for plugins.

Examples - https://yoopta.dev/examples/withCustomPlugin
Concepts - https://yoodocs.space/yoopta-editor/yoopta/introduction-rsK_1fODIL#16e3a5de-4d09-4220-ae5b-71ec82d1c106 

P.S. If you still have plans to implement Table plugin we can have a call about conpcets

**Comment by j7-dev** [comment]
@Darginec05 
Great Work, so nice 👍
ya, I got plan for this, but I'm a bit busy this month. 🙏
so, this issue might takes time to complete.

**Comment by Darginec05** [comment]
Added in v4.8.0
