### ISSUE TITLE
[BUG] Can't embed x.com post

### ISSUE THREAD

**Issue by penghuili** [Darginec05/Yoopta-Editor#165]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Hi, one question about x.com post.

Now the X/Twitter domain becomes x.com everywhere, and when people clicks the "Copy link" of a post, they get a x.com link, not twitter.com anymore.

But the embed plug still only checks `twitter`: https://github.com/Darginec05/Yoopta-Editor/blob/v4.3.1/packages/plugins/embed/src/utils/providers.ts#L34

Should we also check for x.com?

Thank you!

### Steps to Reproduce

1. Go to x.com;
2. Copy the link of a post through the share icon -> "Copy link";
3. You get a x.com link;
4. Add this link to an editor through the embed plugin;
5. You get this:
![Screenshot 2024-05-18 204117](https://github.com/Darginec05/Yoopta-Editor/assets/5326739/000d1d51-8ee4-4cf8-9f5c-d2453951a79a)

### Environment

- OS: Windows 11
- Browser: Vivaldi

### Screenshots

See "Steps to Reproduce"

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Check both "twitter" and "x.com" here to decide it's a X post or not: https://github.com/Darginec05/Yoopta-Editor/blob/v4.3.1/packages/plugins/embed/src/utils/providers.ts#L34

**Comment by Darginec05** [comment]
Oh yes, now all domains with name "twitter" have been moved to `x.com `.
Do you want to start working on it?

**Comment by penghuili** [comment]
> Oh yes, now all domains with name "twitter" have been moved to `x.com `. Do you want to start working on it?

Sure, I will give it a try today.

**Comment by Darginec05** [comment]
Fixed in @v4.3.2 thanks to @penghuili 🔥
