### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by wyvern800** [Darginec05/Yoopta-Editor#169]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Support for multi-languages.

### Proposed Solution

Support for multi-languages.

### Do you want to work on this issue?

No

**Comment by maZahaca** [comment]
Hello @wyvern800! Are you referring to the translation support of the interface?
