### ISSUE TITLE
[BUG] Import error when using nextjs

### ISSUE THREAD

**Issue by madroneropaulo** [Darginec05/Yoopta-Editor#179]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

I'm trying out this library with nextjs in a brand new project from scratch.

When I try to run the script I get this error:
 ```
⨯ ./node_modules/@yoopta/callout/dist/index.js
Attempted import error: 'Elements' is not exported from '@yoopta/editor' (imported as 't').

Import trace for requested module:
./node_modules/@yoopta/callout/dist/index.js
./app/casts/edit/[id]/page.tsx
 GET /casts/edit/123 500 in 34ms
 ⨯ ./node_modules/@yoopta/callout/dist/index.js
Attempted import error: 'Elements' is not exported from '@yoopta/editor' (imported as 't').
```

**NOTE**: I installed the dependencies with npm `--legacy-peer-deps` because otherwise it had some dependencies conflicts with slate.

### Steps to Reproduce

1. Start a new nextjs project from scratch
2. Use this code in that project https://github.com/Darginec05/Yoopta-Editor/blob/master/web/next-example/src/components/examples/withBaseFullSetup/index.tsx.
3. Install dependencies with `npm i @yoopta/callout --legacy-peer-deps`
4. try to run the project: Result you get that error.

P.S. It happens with many plugins, but not with all of them.
Failing:
Callout, lists, embeds, image, video, file.
Working:
Code, Link, Blockquote, Paragraph, Headings

If I comment out the failing components, it works fine.

### Environment

- OS: Macos latest
- Browser: Chrome Latest

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
It looks like you have installed the `.alpha` version of the packages, which is not stable.
Could you please use `@4.4.1 for all packages?

**Comment by madroneropaulo** [comment]
Yeah, that did the trick. Thank you!
