### ISSUE TITLE
[BUG] Unable to use toolbar from mobile

### ISSUE THREAD

**Issue by henryttran** [Darginec05/Yoopta-Editor#182]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Unable to use toolbar from mobile devices (Safari on iPhone)

### Steps to Reproduce

1. Go to https://yoopta-editor.vercel.app/examples/withNotionActionMenu on mobile.
2. Highlight the text you want to edit, and click on any of the styling.
3. None of the toolbar options work.

### Environment

- OS: IOS
- Browser: Safari

### Screenshots

![448111940_1817992865374253_7971829689872516152_n](https://github.com/Darginec05/Yoopta-Editor/assets/16181721/5d1991b8-11f4-4bd9-9d39-370936c6d19f)

### Do you want to work on this issue?

No

**Comment by henryttran** [comment]
Probably a bug introduced in [@yoopta-editor/v4.4.0](https://github.com/Darginec05/Yoopta-Editor/compare/%40yoopta/editor%404.3.2...%40yoopta/editor%404.4.0)

**Comment by Darginec05** [comment]
You was right, it was bug with blur function. 
Thank you! 

Fixed in 4.6.6
Examples: https://yoopta.dev/examples/withCustomToolbar
