### ISSUE TITLE
Sidebar close icon not working always

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [Darginec05/Yoopta-Editor#183]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Clicking on the sidebar close icon doesn't close the sidebar always (screen size). When resizing window, the UI updates (close icon comes and goes based on screen width) but the click handler on close button doesn't work. 
![image](https://github.com/Darginec05/Yoopta-Editor/assets/54144759/28df13bf-b138-4593-8208-204416a0b94c)

### Steps to Reproduce

1. Set window width to 1000px using developer tools. The click handler on close button doesn't work irrespective of reloading the window or not after resizing.
2. Set window width to anywhere <= 990px, after resizing the window the close icon click handler doesn't work. Need to reload the window, and after that it works.

### Environment

- OS: Windows
- Browser: Chrome

### Screenshots

![image](https://github.com/Darginec05/Yoopta-Editor/assets/54144759/fa607e30-8ede-4859-94b4-e2c3ff30ad4e)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Thanks for reporting ˆ-ˆ 
I am really annoyed by this behavior :D

**Comment by Darginec05** [comment]
It's fixed ˆ-ˆ
Check it - https://yoopta.dev/examples/withBaseFullSetup
