### ISSUE TITLE
[BUG] Pasted nested inline images is omitted

### ISSUE THREAD

**Issue by chrassendk** [Darginec05/Yoopta-Editor#184]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When copying a text with an inline image, e.g. an email, and pasting into the Yoopta editor the image block is not recognized and the inline image is omitted.

### Steps to Reproduce

Steps to reproduce

1. Copy a text block with an inline image from e.g. an email
2. Paste in
3. Verify that the image is omitted and not pasted in

### Environment

- OS:
- Browser:

### Screenshots

Console output when pasting: 
<img width="654" alt="image" src="https://github.com/Darginec05/Yoopta-Editor/assets/10469954/31fbf2a9-a96a-43cd-8014-7d412ef04f66">
(Image block is obvious at the bottom)

### Do you want to work on this issue?

No

**Comment by chrassendk** [comment]
When parsing just the image it works, so as soon as it is wrapped with <span> it is omitted.

**Comment by Darginec05** [comment]
Done in v4.6.0
Examples - https://yoopta.dev/examples/withExports
