### ISSUE TITLE
[BUG] Pasting markup string strips markup

### ISSUE THREAD

**Issue by chrassendk** [Darginec05/Yoopta-Editor#185]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When pasting a html string with format e.g. "This is a <b>bold string</b>" renders a stripped string with no bold mark.

### Steps to Reproduce

1. Copy a rendered html string such as "This is a <b>bold string</b>" 
2. Paste in
3. The string will be rendered without a bold tag.

### Environment

- OS:
- Browser:

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.6.0
Examples - https://yoopta.dev/examples/withExports
