### ISSUE TITLE
[FEATURE] Question about adding custom html to the toggle option

### ISSUE THREAD

**Issue by BartoszGl** [Darginec05/Yoopta-Editor#189]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Hello, and first of all thanks for providing such a great library!

I have a question regarding the custom toolbar. In documentation there is a fragment like this in the web/next-example/src/components/Toolbars/MediumToolbar/MediumToolbar.tsx

\<div className={s.root} ref={toolbarRef}>
        <button type="button" className={s.button} onClick={() => editor.formats.bold.toggle()}>
          <span style={editor.formats.bold.isActive() ? { color: '#b5e5a4' } : { color: '#fff' }} className={s.item}>
            <BoldIcon />
          </span>
        </button>
\</div>

I see there is an option to use chosen editor.formats.bold.toggle() and in other examples also some chosen editor.formats options. I would like to add a completely new custom format -> I would like to add a button around highligted text and add a custom id for that button based on some custom logic. Is this possible to extend and write custom formats for my highlighted text? 

### Proposed Solution

No proposed solution, it is more of a question

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Hey @BartoszGl 👋
 I prepared example how to create [custom mark ](https://yoopta.dev/examples/withCustomMark)
 
 Let me know if it helped you

**Comment by BartoszGl** [comment]
Hello @Darginec05 excellent, thanks a lot!

**Comment by Darginec05** [comment]
@BartoszGl with love from open-source 💙
