### ISSUE TITLE
[BUG] Problems when try copy all

### ISSUE THREAD

**Issue by jfortez** [Darginec05/Yoopta-Editor#190]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

On some occasions when you try to copy all the content from the editor, it is not copied

### Steps to Reproduce

I have tried to check when copying everything is not allowed

- when the block is empty and you try to copy everything (ctrl + a) or trying more than once
- rarely when you are in a block that has content, only the content of the block is copied, but the second time it does not copy the other blocks
- when you start the editor, copy all (ctrl + a) and paste some content, select a block and try to copy, sometimes it does not copy the selected block, but it sure does, but the second time you copy everything, it does not copy the other blocks (ctrl + a)

### Environment

- OS: Windows
- Browser: Chrome/Edge

### Screenshots

https://github.com/Darginec05/Yoopta-Editor/assets/69065126/f45939e8-03bf-4e26-bf73-5eb3847a1e0d

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Hi @jfortez!
Which version of @yoopta packages do you use?
I checked it with last versions [here](https://yoopta-editor-leaihdp2n-dargos-projects.vercel.app/examples/withBaseFullSetup) and copying the whole content works

**Comment by jfortez** [comment]
version 4.5.1, I did the demonstration from the demo site (https://yoopta-editor.vercel.app/examples/withBaseFullSetup)

**Comment by Darginec05** [comment]
@jfortez selecting empty block is fixed in new `-rc` version `4.5.2-rc.3` 
Demo - https://yoopta-editor-nmljmwikg-dargos-projects.vercel.app/examples/withBaseFullSetup

**Comment by Darginec05** [comment]
Fixed in v4.6.0
Examples - https://yoopta.dev/examples/withExports
