### ISSUE TITLE
[FEATURE] Justify for align in Paragraph align

### ISSUE THREAD

**Issue by RikidWai** [Darginec05/Yoopta-Editor#199]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Please support justify for align in Paragraph align. It would help this text look nicer. 

### Proposed Solution

Please support justify for align in Paragraph align 

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Okay, working on it 😎

**Comment by Darginec05** [comment]
@RikidWai it's ready in version `v4.6.2`. 

Now you can change align using toolbar.
For void blocks (Image, Video, File, Embed) it's available in dots options
