### ISSUE TITLE
[BUG] Markdown Serializer Strips out asterisks

### ISSUE THREAD

**Issue by sandrews-inc** [Darginec05/Yoopta-Editor#201]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

In the new Yoopta/Exports (current version 4.6.1) the markdown serializer is removing bolded text, and horizontal rules in the markdown it's outputting.

It seems to also miss the bolded text nested within other components like bullet lists when deserializing.

### Steps to Reproduce

1. Add the editor to a page
1. Add some text to the editor with bold words, and horizontal rules
Ex:
```
**Bold Header**
Fun message
***
**Another Bold Header**
Even funner message
```
3. Get the editor value and serialize it to markdown:
```ts
const editorValue = editor?.getEditorValue();
if (editor && editorValue) {
    newContent = markdown.serialize(editor!, editorValue);
    setMarkdownBody(newContent);
}
```
4. Display or log the output markdown and see that the asterisk have all been stripped

### Environment

- OS: MAC OS Sonoma (14.5)
- Browser: Chrome (126.0.6478.127), Safari (17.5)

### Screenshots

Orignal markdown:
![Screenshot 2024-07-02 at 1 09 32 PM](https://github.com/Darginec05/Yoopta-Editor/assets/90924715/fb3c2159-d606-4900-9337-e73de32b2f06)

Deserialized and in the Yoopta Editor:
![Screenshot 2024-07-02 at 1 11 31 PM](https://github.com/Darginec05/Yoopta-Editor/assets/90924715/c61ca78b-383a-4d42-91c9-dd02af801c01)

Serialized back to markdown:
![Screenshot 2024-07-02 at 1 10 25 PM](https://github.com/Darginec05/Yoopta-Editor/assets/90924715/98a25c1a-0537-40bd-ba13-de8259fdc94d)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
hmmm

**Comment by sandrews-inc** [comment]
@Darginec05 Is this on the roadmap to fix? This is currently the only issue blocking my company from implementing this editor. 

We're happy to donate to the cause as well!

**Comment by Darginec05** [comment]
Hi @sandrews-inc 👋
Unfortunately my time is limited, because I have another full-time work.
So your donation will certainly motivate me.

And if this task is urgent for you, I will try to publish version of the fix tomorrow or the day after tomorrow evening.
Thanks in advance! ❤️

**Comment by Darginec05** [comment]
Hi @sandrews-inc 👋
Good news! I published -rc version with this fixes.
Check it in demo - https://yoopta-editor-ffxdyxq73-dargos-projects.vercel.app/examples/withBaseFullSetup

**Comment by Darginec05** [comment]
Added in v4.8.0
Check it in examples https://yoopta.dev/examples/withBaseFullSetup
