### ISSUE TITLE
How to delete Image in content

### ISSUE THREAD

**Issue by garyhav** [Darginec05/Yoopta-Editor#203]
There'is method for upload image (uploadToCloudinary), but no method for delete this image. So if you just remove it with backspace or delete with button it's stays in your storage and take a place. How to implement it?

**Comment by Darginec05** [comment]
This is really good point. 
I think I should add events for blocks someting like `events.on('block:delete')` to subscribe on this and delete image from store

**Comment by garyhav** [comment]
> This is really good point. I think I should add events for blocks someting like `events.on('block:delete')` to subscribe on this and delete image from store

That's great! Can you make it like onUpload property for Image plugin (when implement it as object)

**Comment by garyhav** [comment]
That's great! Can you make it like onUpload property for Image plugin (when implement it as object)

**Comment by Darginec05** [comment]
Hi @garyhav :) 
I forgot to mention here, that's it's done in `v4.8.3` 
I added `onDestroy` method for every plugin.

Check example: `https://yoopta.dev/examples/withPluginEvents`
So, for you cases it can be like this: 

```js
 Image.extend({
    events: {
      onDestroy: (editor, blockId) => {
        const imageElement = Elements.getElement(editor, blockId, { type: 'image' });
        console.log('Image imageElement', imageElement);
        // deleteImageFromCDN(imageElement.src);
      },
    }
  }
  ```

**Comment by garyhav** [comment]
Hi!
Really appreciated this project and the wide functionality of it. Don't
stop to make it better and better!
