### ISSUE TITLE
[FEATURE] Support inline color while export HTML

### ISSUE THREAD

**Issue by j7-dev** [Darginec05/Yoopta-Editor#205]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When I use `html.serialize` to get HTML, the styles missing.

After checking source code, I found that this feature have NOT been implemented.

### Proposed Solution

I've finished a simple solution in my fork `branch: feat/support-inline-color`

please check the diff here https://github.com/j7-dev/Yoopta-Editor/commit/2906860a6b8f1483e29ec6c3adacbd0b4d3e50a7

### Screenshots

![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/c3df70c6-1f83-4c4a-bfc9-381e1f45ea21)

![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/5933329b-a484-4ffb-ab83-dd67192b743d)

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I've made a small solution.

maybe someone can help me go through it

I might take there step
1. move utils function (`highlightToInlineCssAttribute`, `camelToKebab`) to proper directory, any suggestion?
2. Umm...code review and test!?

**Comment by Darginec05** [comment]
Please push PR, I'll check it

**Comment by Darginec05** [comment]
Fixed in v4.9.1
