### ISSUE TITLE
[BUG] If I type ##, the origin content will be removed

### ISSUE THREAD

**Issue by RikidWai** [Darginec05/Yoopta-Editor#206]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

If I have a h1 line and if I would like to change it to h2, can I change it by just adding ## in front of the line? 

If I type ##, the origin content will be removed. Thanks in advance!

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

1. Type # Hello World 
2. Type ## in front of the line 

### Environment

- OS: Windows 
- Browser: Google Chrome

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.8.4
