### ISSUE TITLE
[BUG] embed iframe should have a close tag </iframe> while exporting HTML

### ISSUE THREAD

**Issue by j7-dev** [Darginec05/Yoopta-Editor#207]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Currently, embed will export a `self-close` `<iframe />` tag while exporting HTML which might cause a unexpected result.

And that break my DOM structure, adding a close iframe can fix the  problem.

### Steps to Reproduce

1. Embed a youtube
2. type some word after iframe
3. copy the exporting HTML
4. paste to [HTML](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_editor)

![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/926a3414-e682-4c8b-b1cc-a8544a9b68ac)

### Environment

- OS: Windows
- Browser: Chrome

### Screenshots

![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/738da35d-39e3-4e87-bd1c-d79e2f1ffae1)
![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/926a3414-e682-4c8b-b1cc-a8544a9b68ac)
![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/a2bff480-2504-42c5-ab0d-ef64a2371432)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

1. add close tag
2. check the `deserialize` works as usaul

![圖片](https://github.com/Darginec05/Yoopta-Editor/assets/9213776/1c7df306-01ff-4b36-adf5-a8b1e1b4e11c)

**Comment by Darginec05** [comment]
Hey @j7-dev , thanks for reporting! 
Are you working on this task now?

**Comment by j7-dev** [comment]
Yes, I've made a simple change to this. 
Should I send a PR to you?

**Comment by Darginec05** [comment]
@j7-dev sure! I'll check it and then merge for next patch release

**Comment by Darginec05** [comment]
Thanks for you investigation.
It was fixed in v4.6.5
Examples: https://yoopta.dev/examples/withBaseFullSetup
