### ISSUE TITLE
[BUG] Unable to copy text with editor is read only

### ISSUE THREAD

**Issue by chrassendk** [Darginec05/Yoopta-Editor#208]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Unable to mark and copy text rendered in the editor

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Environment

- OS:
- Browser:

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.7.0 🎉
Example - https://yoopta.dev/examples/withReadOnly
