### ISSUE TITLE
[FEATURE] Add possibility to redefine default props for elements

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yoopta-Editor#220]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As an example, I need to quickly redefine default "target" property in the Link plugin
And now I have to redefine whole render of the link element

### Proposed Solution

I guess would be nice to just extend the plugin and pass the default props (not all of them) that would be merged with the rest of the properties. The Link has a few props, but I wish to redefine only "target".

_I don't insist on the extend variant below, just an example of the idea_

```js
  Link.extend({
    elements: {
       link: {
          props: {
             target: "_blank"
          }
       }
    },
    options: {
      HTMLAttributes: {
        className: 'yoopta-link',
      },
    },
  }),

```

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Added in v4.6.9
Check in examples: https://yoopta.dev/examples/withCustomElementProps
