### ISSUE TITLE
[FEATURE] The selected blocks can't undo

### ISSUE THREAD

**Issue by Nishchit14** [Darginec05/Yoopta-Editor#226]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When I select multiple blocks with mouse drag and hit backslash to remove them. Then I want to undo the changes to revert back all those blocks. Here the undo is not working. 

If mistakenly I remove 10 blocks then I have to re-write then again manually. which it super frustrating tasks to again.

### Proposed Solution

when I hit `ctrl+z` then it should undo.

### Screenshots

![image](https://github.com/user-attachments/assets/408d54b0-21aa-4834-86d6-57b58ebfab9e)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Thanks for reporting issue! 
Working on it

**Comment by Darginec05** [comment]
Implemented in v4.9.0
