### ISSUE TITLE
[BUG] Code plugin highlight will reset

### ISSUE THREAD

**Issue by rezamasoudi** [Darginec05/Yoopta-Editor#235]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When editor wrapping by form tag, code plugin highlight will reset after change language.

### Steps to Reproduce

1. add editor in form tag
2. add code bock
3. open option panel
4. change code language
5. close option panel

### Environment

- OS: windows 10
- Browser: Chrome Version 127.0.6533.74 (Official Build) (64-bit)

### Screenshots

![Screenshot 2024-08-01 153326](https://github.com/user-attachments/assets/d4f54123-5c17-4878-85aa-33b9710baa29)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
@rezamasoudi thanks for reporting issue
Fixed in v4.6.8
