### ISSUE TITLE
[FEATURE] Add methods to programmatically add link into block element

### ISSUE THREAD

**Issue by Oyoha** [Darginec05/Yoopta-Editor#239]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, I wanna create cross-links. When I insert a link to my document and it follows a certain logic, I want the link to change to the name of the document. But I can't change children->text. And to implement my plan, I need to do it.

### Proposed Solution

Make a method or something else that will allow you to change children for links

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
It will possible using next API: `Elements.insertInlineElement()`
Should be added in `v4.7.0`

**Comment by Darginec05** [comment]
Added in v4.8.0
Check examples https://yoopta.dev/examples/withCommandsAPI
