### ISSUE TITLE
[BUG] Yoopta is messing up global styles

### ISSUE THREAD

**Issue by debkanchan** [Darginec05/Yoopta-Editor#240]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

We are using shadcn and consequentially tailwind to build our webapp. As soon as we use any yoopta tool, plugin, mark or editor it messes up global style especially borders

### Steps to Reproduce

- init a next.js project
- setup a theme switcher using next/themes
- setup shadcn/ui
- copy any [block](https://ui.shadcn.com/blocks)
- add a yoopta editor anywhere

### Environment

- OS: MacOS Sonoma 14.5 (23F79)
- Browser: Arc Version 1.54.0 (52220) [Chromium Engine Version 127.0.6533.89]

### Screenshots

before yoopta
<img width="262" alt="Screenshot 2024-08-06 at 9 26 45 PM" src="https://github.com/user-attachments/assets/b02272cc-f3fc-4f5d-8f80-e13cef0cfa46">
<img width="1440" alt="Screenshot 2024-08-06 at 9 27 29 PM" src="https://github.com/user-attachments/assets/170fecbf-5be6-4503-b657-8031a2174554">

after yoopta
<img width="262" alt="Screenshot 2024-08-06 at 9 27 04 PM" src="https://github.com/user-attachments/assets/1c41f3df-b505-45a7-99bc-1e5421d892f8">
<img width="1440" alt="Screenshot 2024-08-06 at 9 27 18 PM" src="https://github.com/user-attachments/assets/be40c225-104f-43d5-8187-d2d7e2c3a3f9">

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Related to https://github.com/Darginec05/Yoopta-Editor/issues/186

**Comment by Darginec05** [comment]
Yes, that's annoying behaviour.
It will be fixed in the next version

**Comment by Darginec05** [comment]
@debkanchan :D

**Comment by Darginec05** [comment]
Hey comrades @g-wozniak @debkanchan!
I just published -rc `4.6.10-rc.0` version with this fix

Could you check it please? 
If everything is good I'll publish stable version today

**Comment by debkanchan** [comment]
Da comrade! It works

![image](https://github.com/user-attachments/assets/15d6e322-d197-4586-96be-afd24a949a38)

**Comment by g-wozniak** [comment]
Works great to me as well. Thanks!

**Comment by Darginec05** [comment]
@debkanchan roger that, I'll prepare stable version
@g-wozniak thanks for sponsoring ❤️

**Comment by Darginec05** [comment]
Fixed in v4.7.0 🎉
