### ISSUE TITLE
[BUG] The code plugin doesn't escape special characters in the HTML output

### ISSUE THREAD

**Issue by rezamasoudi** [Darginec05/Yoopta-Editor#242]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The code plugin does not escape special characters, causing any written code to be executed in the browser. This can lead to potential security vulnerabilities like cross-site scripting (XSS).

### Steps to Reproduce

1. write code in editor
2. export editor content as html
3. paste exported html at  web page and run web page as SSR

### Environment

- OS: windows 10
- Browser: Chrome

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.6.9
Check it in examples: https://yoopta.dev/examples/withBaseFullSetup
