### ISSUE TITLE
[FEATURE] add a feature for upload poster for video and set alt text for images

### ISSUE THREAD

**Issue by rezamasoudi** [Darginec05/Yoopta-Editor#243]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Add an option for upload poster for videos and an option for set image alt text

### Proposed Solution

CK-Editor implemented these features

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Added these features (alt text for Image plugin and poster for Video plugin) in v4.6.9
Check examples: https://yoopta.dev/examples/withBaseFullSetup
