### ISSUE TITLE
[BUG] PROBLEMS RUNNING DEV ON MY LOCAL COMPUTER

### ISSUE THREAD

**Issue by CK-codemax** [Darginec05/Yoopta-Editor#244]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Hi, after I cloned the repository. I ran yarn install, followed by yarn dev.
I got some errors on run of yarn dev.
![localhost_3000_dev - Google Chrome 8_7_2024 9_14_21 PM](https://github.com/user-attachments/assets/b3b8a184-10b7-4276-a494-d8090c5de3ea)
I also got a list of errors on my VScode, the list is quite long though.

I would love if we could write the docs about setting up and running the repo on your local computer, thank you.

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Environment

- OS:
- Browser:

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Hi @CK-codemax! Finally I finally did this :D 
Follow to Contribution Guide - https://github.com/Darginec05/Yoopta-Editor/blob/master/CONTRIBUTING.md
And join to our community - https://discord.com/invite/Dt8rhSTjsn
