### ISSUE TITLE
[Example Request]: How to check if content is empty?

### ISSUE THREAD

**Issue by leo1104** [Darginec05/Yoopta-Editor#246]
### What's the example?

How to check if the content is empty?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Darginec05** [comment]
Hey @leo1104 
I'll create method in Editor API to check if editor is empty in next version.

**Comment by Darginec05** [comment]
Hey @leo1104 
I just published -rc version with new `.isEmpty` API.

API can be found [here](https://github.com/Darginec05/Yoopta-Editor/blob/v4.7.0/packages/core/editor/README.md#editor-api)

### Usage
editor.isEmpty()

**Comment by Darginec05** [comment]
Fixed in v4.7.0 🎉
