### ISSUE TITLE
[BUG] Fix solution for document change detection in YooptaEditor

### ISSUE THREAD

**Issue by Oyoha** [Darginec05/Yoopta-Editor#248]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

You have to compare objects to understand that something has changed. Plus, when adding a new block at the end of the document (when the mouse is clicked), the presence of changes is triggered, since a new block appears (and before we started entering text).
const onEditorChange = (payload: any) => {
if (originalEditorValue !== undefined) {
setIsChanged(!_.isEqual(originalEditorValue, payload))
}
}

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Environment

- OS:
- Browser:

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Added in v4.9.0
Example: https://yoopta.dev/examples/withBaseFullSetup
Source code: https://github.com/Darginec05/Yoopta-Editor/blob/master/web/next-example/src/components/examples/withBaseFullSetup/index.tsx#L123
