### ISSUE TITLE
[BUG] When the list has no content, the cursor is invisible.

### ISSUE THREAD

**Issue by poppynew** [Darginec05/Yoopta-Editor#255]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

For lists, such as unordered lists.
When the list has no content, the cursor is invisible
When the list has content, the cursor is visible
Expected:
Whether the list has content or not, the cursor should be visible

### Steps to Reproduce

1. Create an unordered list
2. The cursor automatically focuses on the unordered list, but it is invisible
3. Enter any character in the unordered list, and the cursor becomes visible

### Environment

- OS: MacOS
- Browser: Chrome

### Screenshots

![img1](https://github.com/user-attachments/assets/5bc02472-0891-443f-9901-10243e36f439)
![img2](https://github.com/user-attachments/assets/c86c2e8a-d89f-48fd-9317-87d204eb0bfc)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.7.0 🎉
