### ISSUE TITLE
[Example Request]: OnChange example

### ISSUE THREAD

**Issue by leo1104** [Darginec05/Yoopta-Editor#263]
### What's the example?

We used to use **OnChange** in V2, but it seems that in V4.7 we have removed it. Can you provide an example of **OnChange** for V4.7?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Darginec05** [comment]
Added in v4.9.0
Example: https://yoopta.dev/examples/withBaseFullSetup
Source code: https://github.com/Darginec05/Yoopta-Editor/blob/master/web/next-example/src/components/examples/withBaseFullSetup/index.tsx#L123
