### ISSUE TITLE
[BUG] Yoopta export - incorrect transformation of HTML to yoopta object

### ISSUE THREAD

**Issue by filipholec** [Darginec05/Yoopta-Editor#264]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When transforming HTML to yoopta editor, there are several problems with the transformed text:
 - tables are not transformed
 - list items are not transformed (in v4.6.9 there was text but styling was lost, e.g. bold / italics / code)

### Steps to Reproduce

Transform the following HTML using @yoopta/export or on https://yoopta.dev/examples/withExports/html
```
<p>To learn any <strong>programming language</strong>, you need to master the knowledge of the so-called <em>three theoretical pillars</em>. Almost all programming languages are built on these pillars:</p>

<ol>
<li><strong>Syntax</strong> (functions, conditions, loops, etc.)</li>
<li><strong>Data types</strong> (numbers, sequences, etc.)</li>
<li><strong>Libraries</strong> (decimal, etc.)</li>
</ol>

<p>First, you&#39;ll look at the second pillar, which is the basics of data types.<br><strong>Data types</strong>, also known as <strong>data structures</strong>. Python is natively equipped with two numeric data types:</p>
<ol>
<li><code>int</code>, whole numbers (from English <em>integer</em>)</li>
<li><code>float</code>, decimal numbers (from English <em>float</em>)</li>
</ol>

<h3>Hierarchy of Operators</h3>
<table>
<thead>
<tr>
<th align="center"><strong>Order</strong></th>
<th align="center"><strong>Operator</strong></th>
<th align="left"><strong>Process</strong></th>
</tr>
</thead>
<tbody><tr>
<td align="center">1.</td>
<td align="center"><code>()</code></td>
<td align="left">Parentheses</td>
</tr>
<tr>
<td align="center">2.</td>
<td align="center"><code>**</code></td>
<td align="left">Exponentiation</td>
</tr>
<tr>
<td align="center">3.</td>
<td align="center"><code>*</code></td>
<td align="left">Multiplication</td>
</tr>
<tr>
<td align="center">4.</td>
<td align="center"><code>/</code></td>
<td align="left">Division</td>
</tr>
<tr>
<td align="center">5.</td>
<td align="center"><code>+</code></td>
<td align="left">Addition</td>
</tr>
<tr>
<td align="center">6.</td>
<td align="center"><code>-</code></td>
<td align="left">Subtraction</td>
</tr>
</tbody></table>
```

### Environment

- version: @yoopta/export v. 4.7.0

### Screenshots

![image](https://github.com/user-attachments/assets/af14d682-847c-4834-bf8d-d0951be03701)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
related https://github.com/Darginec05/Yoopta-Editor/issues/201, https://github.com/Darginec05/Yoopta-Editor/issues/157

**Comment by Darginec05** [comment]
Hi @filipholec 👋
Yeap, Table exports does not work because the plugin is under active development right now.
I have plans to publish `-rc` version for Table in two days :)

**Comment by palwashakmalik** [comment]
is this bug fixed? because I am facing the same issue while deserializing the content from html to editor

**Comment by Darginec05** [comment]
I have published `-rc` version and prepared demo.
Check it here: https://yoopta-editor-ffxdyxq73-dargos-projects.vercel.app/examples/withExports/html

**Comment by Darginec05** [comment]
Done in v4.8.0
