### ISSUE TITLE
[BUG] Link Plugin: Respect element props in Tool Bar

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yoopta-Editor#266]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Additional props of the Link plugin doesn't reflect elementProps that has been redefined in `Link.extend({ elementProps })`

### Steps to Reproduce

1. Redefine elementProps for a Link plugin
```js
  Link.extend({
    elementProps: {
      link: (props) => ({
        ...props,
        target: '_blank',
        url: 'https://',
      }),
    },
  }),
```

2. Add a link to any selected text in editor, check the "Additional props" - it ignores element props!

### Environment

- OS: macOS 14.5 (23F79)
- Browser: Chorme Version 128.0.6613.84 (Official Build) (arm64)

### Screenshots

<img width="526" alt="Screenshot 2024-08-27 at 15 01 24" src="https://github.com/user-attachments/assets/af7ba79b-be7b-4031-b1a7-e92ad1d296a4">

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Done in v4.8.0
