### ISSUE TITLE
[BUG] Not worked action-menu-list, when double tap on backspace button

### ISSUE THREAD

**Issue by voronindim** [Darginec05/Yoopta-Editor#274]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

In edit mode, when setting focus to the first text paragraph, press the backspace button and then press "/", then the additional menu will not be shown
It seems like a small thing, but such presses happen very often when erasing text

### Steps to Reproduce

In edit mode, when setting focus to the first text paragraph, press the backspace button and then press "/", then the additional menu will not be shown
It seems like a small thing, but such presses happen very often when erasing text

### Environment

- OS: all
- Browser: all

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Fixed in v4.9.1.
Reopen issue If bug still appears
