### ISSUE TITLE
[PLUGIN] Embed Plugin don't support instagram posts

### ISSUE THREAD

**Issue by TrickSantos** [Darginec05/Yoopta-Editor#283]
### Is this a unique plugin request?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Proposed Plugin Solution

Add to embed plugin support to instagram posts, currently, I can do a workaround adding this code:

![image](https://github.com/user-attachments/assets/fbd38be4-c57a-46e2-88e2-ea770293230c)

But the content breaks the screen because they have a fixed height

### Screenshots

![image](https://github.com/user-attachments/assets/f4951db1-a6c8-4f15-91e8-ba8fb62b1d84)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
I'll add supporting instagram embeds by default

**Comment by Darginec05** [comment]
Added in v4.8.0
