### ISSUE TITLE
[BUG] Duplicating a block with a code by buttons does not work

### ISSUE THREAD

**Issue by voronindim** [Darginec05/Yoopta-Editor#284]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Duplicating a block with a code by buttons does not work

### Steps to Reproduce

1. create code block
2. tap on more button 
3. tap on duplicate

### Environment

- OS: all
- Browser: all

### Screenshots

<img width="347" alt="Снимок экрана 2024-09-12 в 16 56 55" src="https://github.com/user-attachments/assets/ba601616-9037-4d5e-85ac-41bb2827a42f">
<img width="1055" alt="Снимок экрана 2024-09-12 в 16 57 07" src="https://github.com/user-attachments/assets/35a302d8-bdde-4102-b509-f3d90cb5afbb">

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
wow, strange bug

**Comment by Darginec05** [comment]
Fixed in v4.9.0
