### ISSUE TITLE
[FEATURE] Bash option for codeblock

### ISSUE THREAD

**Issue by trancethehuman** [Darginec05/Yoopta-Editor#286]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There's no `bash` option for the codeblock to store commands for `pnpm` or `pip`.

### Proposed Solution

A bash syntax highlighter

### Screenshots

<img width="868" alt="Screenshot 2024-09-13 at 4 29 30 PM" src="https://github.com/user-attachments/assets/a7423337-0fe7-45f1-8e2d-1f8f2bdada9a">
 
A bash option will go here

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Added in last published `-rc` version.
Demo to check - https://yoopta-editor-morcnd4vu-dargos-projects.vercel.app/examples/withBaseFullSetup

**Comment by Darginec05** [comment]
Added in v4.8.0

**Comment by trancethehuman** [comment]
amazeballs
