### ISSUE TITLE
[BUG]The undo is not working.

### ISSUE THREAD

**Issue by johncodeai** [Darginec05/Yoopta-Editor#300]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

After some operations, the undo is not working.

### Steps to Reproduce

For example:

1. Select multiple blocks with mouse and remove them. Then the undo is not working.
2. Select a normal text and turn it into Heading 1. Then the undo is not working.

I checked the issue history and found similar descriptions:
https://github.com/Darginec05/Yoopta-Editor/issues/226
https://github.com/Darginec05/Yoopta-Editor/issues/232

### Environment

- Browser: Chrome

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
It is currently in development finally

**Comment by Darginec05** [comment]
Added in v4.9.0
