### ISSUE TITLE
[FEATURE] Allow parsers to be extended in Plugin.extend()

### ISSUE THREAD

**Issue by mdwt** [Darginec05/Yoopta-Editor#306]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to be able to replace/override the HTML parsers for plugins. At the moment the `ExtendPlugin` doesn't allow for parsers to be specified, so only the default parsers can be used. 

A simple use case is to use `react-email` components when serializing for email optimized HTML  

### Proposed Solution

Expose `parsers` in `ExtendPlugin` so that one can replace the default parsers if needed.

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Update the ExtendPlugin type..and whatever else needs to happen

**Comment by Darginec05** [comment]
Good point.
I'll add it in the next patch releases

**Comment by Darginec05** [comment]
hey @mdwt  👋 
We built fully functional `Email-Builder` via `@yoopta/email-editor`
Check it out in examples: `https://yoopta.dev/examples/withEmailBuilder/email-builder`
