### ISSUE TITLE
[BUG] New packages table and divider override global styles

### ISSUE THREAD

**Issue by filipholec** [Darginec05/Yoopta-Editor#311]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

New plugins @yoopta/table and @yoopta/divider override global definitions of classes. Since we're using Tailwind, the new classes override our pre-existing classes and it also affects hidden elements.

Our main concerns are `.flex` class, but there are more included:

For `@yoopta/divider`
```
.mr-2{margin-right:.5rem}.block{display:block}.flex{display:flex}.h-4{height:1rem}.w-4{width:1rem}.justify-between{justify-content:space-between}
```

And for `@yoopta/table`:
```
.mr-2{margin-right:.5rem}.block{display:block}.inline{display:inline}.flex{display:flex}.table{display:table}.table-row{display:table-row}.h-4{height:1rem}.h-\[14px\]{height:14px}.w-4{width:1rem}.w-\[14px\]{width:14px}.flex-shrink-0{flex-shrink:0}.rotate-180{--tw-rotate:180deg}.rotate-180,.transform{transform:translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}.justify-between{justify-content:space-between}.blur{--tw-blur:blur(8px)}.blur,.filter{filter:var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)}
```

I suggest adding `yoopta-` prefix to classes mentioned above.

### Steps to Reproduce

Written in Description

### Environment

- OS: Linux
- Browser: Brave

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
oh!

**Comment by Darginec05** [comment]
It's already fixed
I'll release tomorrow patch version

**Comment by filipholec** [comment]
Great, glad to hear that :slightly_smiling_face:

**Comment by Darginec05** [comment]
@filipholec it's done in v4.8.3 :)
