### ISSUE TITLE
[BUG] when copying and pasting the tab freezes

### ISSUE THREAD

**Issue by Quietscher** [Darginec05/Yoopta-Editor#315]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Steps to reproduce:
- write sth
- copy with cmd+a cmd+c cmd+v
- repeat 3-4 times
- Browsertab freezes

### Steps to Reproduce

Steps to reproduce:
- write sth
- copy with cmd+a cmd+c cmd+v
- repeat 3-4 times
- Browsertab freezes

### Environment

- OS: macOS
- Browser: chromium / ARC

### Screenshots

Nothing to screenshot

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Could you recheck it please with v4.9.0 or in [examples](https://yoopta.dev/examples/withBaseFullSetup)?
It seems it was fixed with 4.9.0

Reopen issue if the bug still appears
