### ISSUE TITLE
[BUG] ActionMenu position does not change with height change

### ISSUE THREAD

**Issue by johncodeai** [Darginec05/Yoopta-Editor#327]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

If the input characters cause the height of the ActionMenu to change, its position will not adjust accordingly, resulting in a blank space in the middle.
<img width="375" alt="image" src="https://github.com/user-attachments/assets/e3bc8b88-831e-4d8a-9f4f-69dac742df22">

### Steps to Reproduce

1. Enter "/" at the bottom of the article to trigger the ActionMenu
3. Enter 'h2' to filter the content and change the height of the ActionMenu

### Environment

- Browser: Chrome

### Do you want to work on this issue?

No

**Comment by mdsaban** [comment]
I’m experiencing the same issue. If it hasn’t been picked up yet, I’m happy to take a look into it. @Darginec05

**Comment by Darginec05** [comment]
@mdsaban let's go!! 
I'll be happy with your contributions 😎

**Comment by Darginec05** [comment]
Fixed in v4.8.4
