### ISSUE TITLE
[BUG] Contributor code of conduct hyperlink in contributing docs returns 404 code

### ISSUE THREAD

**Issue by Cthomp7** [Darginec05/Yoopta-Editor#343]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The "Contributor Code of Conduct" hyperlink when clicked returns a 404 page not found error. 
- Page with hyperlink: https://yoodocs.space/yoopta-editor/yoopta/contributing-0JsXmtq8q_?v=1.0.0&lang=en
- Redirect link: https://yoopta.dev/examples/withExports/CODE_OF_CONDUCT.md

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
fixed. thanks!
