### ISSUE TITLE
[BUG] No return value from @yoopta/exports markdown with basic example

### ISSUE THREAD

**Issue by snewcomer** [Darginec05/Yoopta-Editor#346]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Happy to contribute any docs.   Working from the example on 4.8.4 [here](https://github.com/Darginec05/Yoopta-Editor/blob/master/packages/core/exports/README.md), but am not seeing a return value.  Am I missing any plugins or marks to make this work that I can help document?

```
  const jsonValue = markdown.deserialize(editor, '<h1>First title</h1>');
  console.log("yoopta", jsonValue)
  return (
```

<img width="322" alt="Screenshot 2024-10-11 at 7 28 39 AM" src="https://github.com/user-attachments/assets/ec50966a-4a4c-45b6-9f81-2c37eb0021db">

### Steps to Reproduce

Install 4.8.4
Chrome browser (latest)

```
plugins = [Paragraph, Blockquote, Image, Link, HeadingOne, HeadingThree, HeadingTwo, NumberedList, BulletedList, TodoList/*, Headings, List*/, Divider, Table, Accordion]

const TOOLS = {
  Toolbar: {
    tool: Toolbar,
    render: DefaultToolbarRender,
  },
  ActionMenu: {
    tool: ActionMenu,
    render: DefaultActionMenuRender,
  },
  LinkTool: {
    tool: LinkTool,
    render: DefaultLinkToolRender,
  },
};

const MARKS = [Bold, Italic, CodeMark, Underline, Strike, Highlight];
```

<img width="213" alt="Screenshot 2024-10-11 at 7 45 14 AM" src="https://github.com/user-attachments/assets/d987abe2-e427-4a7c-ad48-958343179774">

### Screenshots

<img width="322" alt="Screenshot 2024-10-11 at 7 28 39 AM" src="https://github.com/user-attachments/assets/ca52b0ca-fc8a-4292-86c2-7439c8e0fc09">

### Do you want to work on this issue?

Yes

**Comment by snewcomer** [comment]
Whoops sry that was my last failed experiment (that I got wrong!  thx).  Here is what I have now.

```
  const htmlValue = html.deserialize(editor, '<h1>First title</h1>');
  console.warn("yoopta html", htmlValue)
  const mdValue = markdown.deserialize(editor, '## First markdown title');
  console.warn("yoopta md", mdValue)
```

<img width="363" alt="Screenshot 2024-10-11 at 8 14 43 AM" src="https://github.com/user-attachments/assets/8cf87a92-9a7c-4ab7-afcc-bb996157bf6c">

**Comment by Darginec05** [comment]
@snewcomer hmm, strange, I used the same code that you sent and it works

<img width="827" alt="Screenshot 2024-10-11 at 15 32 12" src="https://github.com/user-attachments/assets/82c7a080-730d-4610-9f2a-9399992a8ccc">

**Comment by Darginec05** [comment]
@snewcomer oh, I see that you are using `deserialize` methods inside component that re-rendered every time, try using it in `useEffect` or in some `onClick` event to log it

**Comment by snewcomer** [comment]
To no avail.

![Screenshot 2024-10-11 at 11 19 25 AM](https://github.com/user-attachments/assets/8d4ced48-0c40-4a9b-8674-1e715ceac8cc)
![Screenshot 2024-10-11 at 11 21 02 AM](https://github.com/user-attachments/assets/23a1837d-611c-4cda-9cde-0013422d775e)

**Comment by snewcomer** [comment]
https://github.com/Darginec05/Yoopta-Editor/blob/67365a6d15fa01b0a76c9bf3a93a66f1f41f208b/packages/core/exports/src/html/deserialize.ts#L134


```
```

**Comment by snewcomer** [comment]
ack you were right.  inside useEffect.  `plugins` were not there yet (presumably to transform into a `isYooptaBlock `) so `{ text }` was the only object coming out

**Comment by Darginec05** [comment]
@snewcomer cool!
