### ISSUE TITLE
[BUG] Two clicks are needed to focus the cursor on the code block

### ISSUE THREAD

**Issue by johncodeai** [Darginec05/Yoopta-Editor#355]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When you leave A Block and then click on the code block, the cursor remains in A Block.

Expected: When clicking on the code block for the first time, the cursor focuses on the position in the clicked code block.

### Do you want to work on this issue?

No

**Comment by johncodeai** [comment]
After upgrading to v4.9.2, the problem seems to be solved.

**Comment by johncodeai** [comment]
After upgrading to v4.9.2, the problem seems to be solved.

**Comment by Darginec05** [comment]
super :)
