### ISSUE TITLE
[BUG] 'findPluginBlockByPath' is not exported from '@yoopta/editor'

### ISSUE THREAD

**Issue by rafayexalter** [Darginec05/Yoopta-Editor#360]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Wanted to add action menu list but it is showing this error

[https://yoodocs.space/yoopta-editor/yoopta/get-started-eH9NxTHkJH?v=1.0.0&lang=en](url)

![Screenshot 2024-10-26 065955](https://github.com/user-attachments/assets/f0c2edc9-97fe-44cf-9a43-ff779332b6e4)

Using next.js latest version

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
fixed in v4.9.0
