### ISSUE TITLE
[BUG] Action menu does not render properly with shortcuts 

### ISSUE THREAD

**Issue by mdsaban** [Darginec05/Yoopta-Editor#367]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

After entering "h1" after the "/", if you press backspace to change it to "h2," it doesn't work correctly. The same issue occurs if I enter "heading1" and then backspace to change it to another block; the action menu doesn't render properly.

### Screenshots

https://github.com/user-attachments/assets/1dffe6d0-7ec0-4524-93b1-1025c234322d

### Do you want to work on this issue?

Yes

**Comment by Darginec05** [comment]
Thanks for reporting
It seems it already fixed in https://github.com/Darginec05/Yoopta-Editor/issues/362

**Comment by Darginec05** [comment]
I'll release patch version today

**Comment by Darginec05** [comment]
Fixed in `v4.9.1` 
Reopen issue If bug still appears
