### ISSUE TITLE
Custom Block

### ISSUE THREAD

**Issue by Harismehmoodulhaq** [Darginec05/Yoopta-Editor#44]
Hi Guys,

can any one tell me how can we make custom block

Thanks in advance!

**Comment by Darginec05** [comment]
Hi @Harismehmoodulhaq.
It will be possible in v2

**Comment by Darginec05** [comment]
Stand by. 
[Version 2 is ready for release](https://github.com/Darginec05/Yopta-Editor/issues/48)

**Comment by Darginec05** [comment]
This is done in v4.0.0

Check example with custom divider plugin:
- https://stackblitz.com/edit/vitejs-vite-syjdcx
