### ISSUE TITLE
Yoopta@V2 is coming ❗

### ISSUE THREAD

**Issue by Darginec05** [Darginec05/Yoopta-Editor#48]
## Hi everyone 👋

I am working on the release of the second version.
The v2 version contains a lot of cool features and solutions with requests from developers :blue_heart:

----
### Features in v2:
- Package renamed and moved to scoped package name @yoopta. Example: `@yoopta/editor, @yoopta/callout` and other..
- Multipackages to reduce bundlesize and just import exactly what you need. 
- You will be able create your custom plugin using function `createYoptaPlugin` 
- You can easily modify or extend existing plugins. `Paragraph.extend({ renderer: MyCustomParagraph, shortcut: 'text' })`
- Available packages:
   - Image
   - Video
   - Paragraph
   - Embed
   - Lists (Ordered, Bulleted and Todo) with nested behaviour
   - Headings
   - Callout
   - Code Syntax Highlight
   - Blockquote
   - Link
- I always care about page performance. Thus, each plugin includes two types of rendering `editor` and `render`. So, this means that when you create any blogging platform, you can only use `@yopta/renderer` for quests, and it will remove all the editor tools for fast rendering and page perfomance
- Nested drag and drop feature
- Image, Embed and Video are now plugins on steroid. They include cool edit features like resizing, lazy loading and parsers.  
- Code Syntax Highlight include 10+ languages 
- Good copy/paste functionality and `@yopta/exports` package for deserailize and serialize html or markdown data.
- Easy peasy configured marks for text transform
- `<ActionMenu />` which triggered by "/" include custom rendering and list of plugins what you need
- `<Toolbar />` also include custom rendering and list of makrs what you need. 
- Custom ElementOptions for every node (work in progress)
- Tests configuration (work in progress)
- And ChatGPT plugin :heart_eyes: It will include two packages: for frontend side and backend! (Work in progress).

`And many other features...` :sparkles:

--- 

### So, the main challenge for me is to make life easier for developers so that you can create any rich editor without tears and with full UI customization. 
So, don't forget ask for any feature or reporting issues :v:

----- 
:innocent: Before publishing the v2 version, I want to create a release candidate to test it in production and understand what else developers need, what functionality they still need for comfortable work.

:exclamation: If you already use Yopta-Editor@v1 don't afraid because I'll prepare migration guide from v1 to v2

:computer: Current available [demo's](https://yopta-editor.vercel.app/examples/withBasicExample)

**Comment by Artmadiar** [comment]
i'm really looking forward to the new version!!!

**Comment by ofgowtham** [comment]
Thanks :))))

**Comment by amulyaparmar** [comment]
I am so excited!! As always Darcine, incredible work!

**Comment by MarcellinoCO** [comment]
Stumbled upon this repository while searching for an intuitive editor. What a hidden gem!
Can't wait to try the new version!

**Comment by GVALFER** [comment]
Is it dead or what?


# npm install yopta-editor
npm ERR! code ENOVERSIONS
npm ERR! No versions available for yopta-editor

**Comment by gozup** [comment]
Hello @Darginec05 

First, congratulation and thank you for your work.
I was wondering is you have any ETA to share about the V2 release, or any public roadmap to follow the progression?

Thanks again, wish you all the best!

**Comment by Darginec05** [comment]
Hello @gozup 
Sorry for the late response

My answer is about the current status and the future of this project. 

After several issues and feedback, I put everything together and came up with a new major @v4 version, where the editor has become much better (despite some current bugs)

Our Roadmap: 
- Develop other powerful plugins
- AI tools
- Simplify API for creating plugins
- Collabrative mode
- Plugin system
- Optimizations for media components
- Rethink approach for just rendering to increase SEO perfomance
- Continue improving the project. We are listening to you and your requests 💙

Check demos: 
- https://yoopta-editor.vercel.app/

Release of @v4
- https://github.com/Darginec05/Yoopta-Editor/releases/tag/%40yoopta%2Feditor%404.0.0
