### ISSUE TITLE
Portrait images is always in 1:1 aspect ratio instead of being responsive

### ISSUE THREAD

**Issue by legowtham** [Darginec05/Yoopta-Editor#63]
Describe the bug
Image editor container should have proper scaling support for both landscape and portrait images, Portrait images and some times landscape images looks like scaled in a square layout.
Editor should adapt to the dimension with respect to the image's dimenstion.

To Reproduce

add a portrait image to the editor, it will be scaled to a squared image

When i tried to add this image to the editor: [Image](https://images.unsplash.com/photo-1618042164219-62c820f10723)

https://github.com/Darginec05/Yopta-Editor/assets/24489435/299fd1c9-ace9-4035-a616-d7b6d8dc7b8f

Expected behavior
The resizer should be responsive to all image dimensions.

Screenshots

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browser: Chrome 113.0.5672.93
Version : 
    "@stripe/stripe-js": "^1.52.1",
    "@yoopta/action-menu-list": "^1.9.5-rc",
    "@yoopta/blockquote": "^1.9.6-rc",
    "@yoopta/callout": "^1.9.5-rc",
    "@yoopta/code": "^1.9.5-rc",
    "@yoopta/editor": "1.9.9-rc",
    "@yoopta/embed": "^1.9.5-rc",
    "@yoopta/headings": "^1.9.5-rc",
    "@yoopta/image": "^1.9.5-rc",
    "@yoopta/link": "^1.9.5-rc",
    "@yoopta/lists": "^1.9.5-rc",
    "@yoopta/marks": "^1.9.5-rc",
    "@yoopta/paragraph": "^1.9.7-rc",
    "@yoopta/renderer": "^1.9.5-rc",
    "@yoopta/toolbar": "^1.9.5-rc",
    "@yoopta/video": "^1.9.5-rc",

**Comment by Darginec05** [comment]
This task is done in @v4.0.0
I have done options for Image plugin to control image view

Check demos:
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup
