### ISSUE TITLE
Code block not color formatted with respect to prgramming language/syntax

### ISSUE THREAD

**Issue by legowtham** [Darginec05/Yoopta-Editor#68]
Describe the bug:

Code block not formatted with respect to prgramming language when pasting the code, it just shows in white text.

To Reproduce

Add code from slash command, copy paste some programming code.
Strangely, it 'partially' works when we do "Paste as plain text", but color goes white when rendered with <YoptaRenderer />

You can see the issue with the below video:

https://github.com/Darginec05/Yopta-Editor/assets/24489435/788b512e-01bc-42d5-8bce-8619e68e24a7

Expected behavior
Whether pasted with "Paste" or "Paste with plain text", it should be color formatted and with a right syntax.

Screenshots

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browser: Chrome 113.0.5672.93
Version : 
    "@yoopta/action-menu-list": "^1.9.10-rc",
    "@yoopta/callout": "^1.9.10-rc",
    "@yoopta/code": "^1.9.10-rc",
    "@yoopta/editor": "1.9.14-rc",
    "@yoopta/embed": "^1.9.10-rc",
    "@yoopta/headings": "^1.9.10-rc",
    "@yoopta/image": "^1.9.10-rc",
    "@yoopta/link": "^1.9.10-rc",
    "@yoopta/link-tool": "^1.9.3-rc",
    "@yoopta/lists": "^1.9.10-rc",
    "@yoopta/marks": "^1.9.10-rc",
    "@yoopta/paragraph": "^1.9.12-rc",
    "@yoopta/renderer": "^1.9.10-rc",
    "@yoopta/toolbar": "^1.9.10-rc",
    "@yoopta/video": "^1.9.10-rc",

**Comment by Darginec05** [comment]
Will be fixed in https://github.com/Darginec05/Yopta-Editor/issues/101

**Comment by Darginec05** [comment]
This task is done 😎
Check it 

Versions:
- yoopta/editor@4.0.0
- yoopta/code@4.0.0

Demos:
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup
