### ISSUE TITLE
Expand action menu when clicking plus

### ISSUE THREAD

**Issue by tylerhunt** [Darginec05/Yoopta-Editor#77]
It would be nice if clicking the plus would open a menu to choose which type of block to add instead of always adding a paragraph.

**Comment by Darginec05** [comment]
Related to https://github.com/Darginec05/Yoopta-Editor/issues

**Comment by Darginec05** [comment]
Fixed in [v4.1.0](https://github.com/Darginec05/Yoopta-Editor/releases/tag/v4.1.0)
