### ISSUE TITLE
Copy and pasting Code block from vscode not formatting properly 

### ISSUE THREAD

**Issue by legowtham** [Darginec05/Yoopta-Editor#79]
**Describe the bug**

Code block not formatted properly when pasting the code from vscode (or anywhere), it just shows in white text when paste and formatted partially when paste as plain text

**To Reproduce**

1. Copy code from vscode
2. Paste it in the Yopta Editor

**Screenshots**

https://github.com/Darginec05/Yopta-Editor/assets/24489435/cf173a7d-f120-4c56-9586-3ee3211b8c0b

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browser: Chrome 113.0.5672.93
Version :
"@stripe/stripe-js": "^1.52.1",
"@yoopta/action-menu-list": "^1.9.5-rc",
"@yoopta/blockquote": "^1.9.6-rc",
"@yoopta/callout": "^1.9.5-rc",
"@yoopta/code": "^1.9.5-rc",
"@yoopta/editor": "1.9.9-rc",
"@yoopta/embed": "^1.9.5-rc",
"@yoopta/headings": "^1.9.5-rc",
"@yoopta/image": "^1.9.5-rc",
"@yoopta/link": "^1.9.5-rc",
"@yoopta/lists": "^1.9.5-rc",
"@yoopta/marks": "^1.9.5-rc",
"@yoopta/paragraph": "^1.9.7-rc",
"@yoopta/renderer": "^1.9.5-rc",
"@yoopta/toolbar": "^1.9.5-rc",
"@yoopta/video": "^1.9.5-rc",

**Comment by Darginec05** [comment]
Will be fixed in https://github.com/Darginec05/Yopta-Editor/issues/101

**Comment by Darginec05** [comment]
This task is done

Versions:
 - yoopta/editor@4.0.0
 - yoopta/code@4.0.0

Demos:
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup
