### ISSUE TITLE
Can't scroll page when action menu is open

### ISSUE THREAD

**Issue by tylerhunt** [Darginec05/Yoopta-Editor#80]
Sometimes the action menu extends beyond the page bounds, but when the action menu is open, the page cannot be scrolled.

The page should still be scrollable when the action menu is open.

**Comment by Darginec05** [comment]
I have plans to add option to switch this behaviour

**Comment by Darginec05** [comment]
Fixed in v4.0.0
Check in demos: 
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup
