### ISSUE TITLE
Changing text to list causes crash

### ISSUE THREAD

**Issue by tylerhunt** [Darginec05/Yoopta-Editor#81]
Selecting text and then attempting to change its element to a numbered list or bulleted list causes the editor to crash (and disappear) with the following errors:

<details>
<summary>[Error] IndexSizeError: The index is not in the allowed range.</summary>
<pre>
	(anonymous function) (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:58615)
	callCallback (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:39945)
	dispatchEvent
	invokeGuardedCallbackDev (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:39994)
	invokeGuardedCallback (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:40058)
	reportUncaughtErrorInDEV (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:58614)
	captureCommitPhaseError (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62902)
	commitPassiveMountEffects_complete (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:60669)
	commitPassiveMountEffects_begin (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:60654)
	commitPassiveMountEffects (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:60642)
	flushPassiveEffectsImpl (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62815)
	flushPassiveEffects (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62760)
	commitRootImpl (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62711)
	commitRoot (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62458)
	performSyncWorkOnRoot (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:61893)
	performSyncWorkOnRoot
	flushSyncCallbacks (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:47823)
	(anonymous function) (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:61427)
</pre>
</details>

<details>
<summary>[Error] The above error occurred in the <G> component:</summary>
<pre>
G@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88998:11678
@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88789:12509
div
Bn@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88789:27890
It@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88789:9543
at@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88783:23081
Slate@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:79720:11
ir@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88789:41428
P@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88777:90
ar@http://domain.test/packs/js/vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:88789:48112
Editor@http://domain.test/packs/js/application.js:173:61

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
	logCapturedError (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:54468)
	(anonymous function) (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:54496)
	callCallback (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:49704)
	commitUpdateQueue (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:49725)
	commitLayoutEffectOnFiber (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:59167)
	commitLayoutMountEffects_complete (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:60464)
	commitLayoutEffects_begin (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:60450)
	commitLayoutEffects (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:60388)
	commitRootImpl (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62599)
	commitRoot (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:62458)
	performSyncWorkOnRoot (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:61893)
	performSyncWorkOnRoot
	flushSyncCallbacks (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:47823)
	(anonymous function) (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:61427)
</pre>
</details>

<details>
<summary>[Error] IndexSizeError: The index is not in the allowed range.</summary>
<pre>
	flushSyncCallbacks (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:47837)
	(anonymous function) (vendors-node_modules_hotwired_stimulus-webpack-helpers_dist_stimulus-webpack-helpers_js-node_-2874a7.js:61427)
</pre>
</details>

**Comment by Darginec05** [comment]
I need a little more information.
Have you changed the text to list using the ActionMenu on the Toolbar?
And which version is "@yoopta/editor` are you using?
