### ISSUE TITLE
Getting the editor instance and performing operations 

### ISSUE THREAD

**Issue by abdulmoonah** [Darginec05/Yoopta-Editor#92]
**Is your feature request related to a problem? Please describe.**
always frustrated when trying to get the editor or Editable instance used by YooptaEditor Component so I can perform operation such as get cursor position, insert or remove block of text. 

**Describe the solution you'd like**
Ideally if I can get the Editable instance used in the YooptaEditor component so I can do something like:
`    const isAstChange = editor.operations.some((op) => 'set_selection' !== op.type);
`
or Using a `ref` as it is commonly done with slate editor. Please suggest if theres a better way to achieve this.

**Describe alternatives you've considered**
I have tried using js DOM to select the `div` element by `id` but it does not seem to select it.

**Comment by Darginec05** [comment]
This task is done. Thanks you for reporting!
Now you have editor instance and you can manipulate with content programmatically 

Check demos: 
 - https://yoopta-editor.vercel.app/examples/withEditorControl

Source code for this example
 - https://github.com/Darginec05/Yoopta-Editor/blob/master/web/next-example/src/components/examples/withEditorControl/index.tsx
