### ISSUE TITLE
Code block lost it's syntax highlighting when using Renderer

### ISSUE THREAD

**Issue by mbahArip** [Darginec05/Yoopta-Editor#96]
**Description**
The syntax highlighting are working properly when it's rendered using the `@yoopta/editor`, but it lost the syntax highlighting when rendered on `@yoopta/renderer`

I'm saving the data into the database by stringify the JSON, then I parse the JSON back to be used on the renderer

**Version Info**
OS: Windows 11
Browser: Ms Edge
"@yoopta/editor": "^1.9.26-rc",
"@yoopta/code": "^1.9.15-rc",
"@yoopta/renderer": "^1.9.17-rc",

**Screenshots**
When using editor
![image](https://github.com/Darginec05/Yopta-Editor/assets/62494292/e6f3221f-fadb-4c55-8f34-96a67db3b0f9)

When using renderer
![image](https://github.com/Darginec05/Yopta-Editor/assets/62494292/f1509055-f846-4f1b-9503-bc8663c02598)

**Comment by Darginec05** [comment]
Will be fixed in https://github.com/Darginec05/Yopta-Editor/issues/101

**Comment by Darginec05** [comment]
This task is done 😎
Check it 

Versions:
- yoopta/editor@4.0.0
- yoopta/code@4.0.0

Demos:
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup
